backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
site_url: https://peaceful-chandrasekhar-c3eb30.netlify.app
display_url: https://peaceful-chandrasekhar-c3eb30.netlify.app
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders
  # Required - a list of locales to show in the editor UI
  locales: [en, de, es]
  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en
media_folder: src/assets
public_folder: /assets
collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page" # Used in the UI, ie: "New Post"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - { label: "Cover", name: "cover", widget: "image", required: false}
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown"}

